/*

	Ethnic Diversity
	Mod Compatibility file
	by Nutty (2016)

	Adjust size, formation, number of figures for various mods

*/

/*
--Prehistoric Era
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitInfoType = 'ART_DEF_UNIT_SAVAGE' || SUBSTR(UnitInfoType, 19) || '_ED' 
	WHERE UnitInfoType LIKE 'ART_DEF_UNIT_SAVAGE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SAVAGE' || SUBSTR(UnitInfoType, 27) || '_ED' 
	WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SAVAGE%';
UPDATE ArtDefine_UnitInfos SET Type = 'ART_DEF_UNIT_SAVAGE' || SUBSTR(UnitInfoType, 19) || '_ED' 
	WHERE Type LIKE 'ART_DEF_UNIT_SAVAGE%';
UPDATE ArtDefine_UnitMemberCombats SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_SAVAGE' || SUBSTR(UnitInfoType, 27) || '_ED' 
	WHERE UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_SAVAGE%';
UPDATE ArtDefine_UnitMemberCombatWeapons SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_SAVAGE' || SUBSTR(UnitInfoType, 27) || '_ED' 
	WHERE UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_SAVAGE%';
UPDATE ArtDefine_UnitMemberInfos SET Type = 'ART_DEF_UNIT_MEMBER_SAVAGE' || SUBSTR(UnitInfoType, 27) || '_ED' 
	WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SAVAGE%';
UPDATE ArtDefine_StrategicView SET StrategicViewType = 'ART_DEF_UNIT_SAVAGE' || SUBSTR(UnitInfoType, 19) || '_ED' 
	WHERE StrategicViewType LIKE 'ART_DEF_UNIT_SAVAGE%';

--Renaissance Era Revised
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitInfoType = 'ART_DEF_UNIT_2HANDER' || SUBSTR(UnitInfoType, 20) || '_ED' 
	WHERE UnitInfoType LIKE 'ART_DEF_UNIT_2HANDER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_2HANDER' || SUBSTR(UnitInfoType, 28) || '_ED' 
	WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_2HANDER%';
UPDATE ArtDefine_UnitInfos SET Type = 'ART_DEF_UNIT_2HANDER' || SUBSTR(UnitInfoType, 20) || '_ED' 
	WHERE Type LIKE 'ART_DEF_UNIT_2HANDER%';
UPDATE ArtDefine_UnitMemberCombats SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_2HANDER' || SUBSTR(UnitInfoType, 28) || '_ED' 
	WHERE UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_2HANDER%';
UPDATE ArtDefine_UnitMemberCombatWeapons SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_2HANDER' || SUBSTR(UnitInfoType, 28) || '_ED' 
	WHERE UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_2HANDER%';
UPDATE ArtDefine_UnitMemberInfos SET Type = 'ART_DEF_UNIT_MEMBER_2HANDER' || SUBSTR(UnitInfoType, 28) || '_ED' 
	WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_2HANDER%';
UPDATE ArtDefine_StrategicView SET StrategicViewType = 'ART_DEF_UNIT_2HANDER' || SUBSTR(UnitInfoType, 20) || '_ED' 
	WHERE StrategicViewType LIKE 'ART_DEF_UNIT_2HANDER%';

--Enlightenment Era
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitInfoType = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' WHERE 
	(UnitInfoType LIKE 'ART_DEF_UNIT_EE_CARRACK%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_EE_CUIRASSIER%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_EE_FIELD_GUN%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_EE_GALLEON%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_EE_LINE_INFANTRY%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_EE_SKIRMISHER%');
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_CARRACK%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_CUIRASSIER%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_FIELD_GUN%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_GALLEON%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_LINE_INFANTRY%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EE_SKIRMISHER%');
UPDATE ArtDefine_UnitInfos SET Type = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' WHERE 
	(Type LIKE 'ART_DEF_UNIT_EE_CARRACK%' OR 
	Type LIKE 'ART_DEF_UNIT_EE_CUIRASSIER%' OR 
	Type LIKE 'ART_DEF_UNIT_EE_FIELD_GUN%' OR 
	Type LIKE 'ART_DEF_UNIT_EE_GALLEON%' OR 
	Type LIKE 'ART_DEF_UNIT_EE_LINE_INFANTRY%' OR 
	Type LIKE 'ART_DEF_UNIT_EE_SKIRMISHER%');
UPDATE ArtDefine_UnitMemberCombats SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_CARRACK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_CUIRASSIER%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_FIELD_GUN%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_GALLEON%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_LINE_INFANTRY%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_SKIRMISHER%');
UPDATE ArtDefine_UnitMemberCombatWeapons SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_CARRACK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_CUIRASSIER%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_FIELD_GUN%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_GALLEON%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_LINE_INFANTRY%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_EE_SKIRMISHER%');
UPDATE ArtDefine_UnitMemberInfos SET Type = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(Type LIKE 'ART_DEF_UNIT_MEMBER_EE_CARRACK%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_EE_CUIRASSIER%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_EE_FIELD_GUN%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_EE_GALLEON%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_EE_LINE_INFANTRY%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_EE_SKIRMISHER%');
UPDATE ArtDefine_StrategicView SET StrategicViewType = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' 
	WHERE StrategicViewType IN 
	('ART_DEF_UNIT_EE_CARRACK', 'ART_DEF_UNIT_EE_CUIRASSIER', 'ART_DEF_UNIT_EE_FIELD_GUN', 
	'ART_DEF_UNIT_EE_GALLEON', 'ART_DEF_UNIT_EE_LINE_INFANTRY', 'ART_DEF_UNIT_EE_SKIRMISHER');

--Future Worlds
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitInfoType = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' WHERE 
	(UnitInfoType LIKE 'ART_DEF_UNIT_FW_CYBORG%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_FW_HOVERTANK%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_FW_RAILGUN_TANK%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_FW_SUPERCARRIER%' OR 
	UnitInfoType LIKE 'ART_DEF_UNIT_FW_VERTOL%');
UPDATE ArtDefine_UnitInfoMemberInfos SET UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FW_CYBORG%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FW_HOVERTANK%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FW_RAILGUN_TANK%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FW_SUPERCARRIER%' OR 
	UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FW_VERTOL%');
UPDATE ArtDefine_UnitInfos SET Type = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' WHERE 
	(Type LIKE 'ART_DEF_UNIT_FW_CYBORG%' OR 
	Type LIKE 'ART_DEF_UNIT_FW_HOVERTANK%' OR 
	Type LIKE 'ART_DEF_UNIT_FW_RAILGUN_TANK%' OR 
	Type LIKE 'ART_DEF_UNIT_FW_SUPERCARRIER%' OR 
	Type LIKE 'ART_DEF_UNIT_FW_VERTOL%');
UPDATE ArtDefine_UnitMemberCombats SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED'  WHERE 
	(UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_CYBORG%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_HOVERTANK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_RAILGUN_TANK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_SUPERCARRIER%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_VERTOL%');
UPDATE ArtDefine_UnitMemberCombatWeapons SET UnitMemberType = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_CYBORG%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_HOVERTANK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_RAILGUN_TANK%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_SUPERCARRIER%' OR 
	UnitMemberType LIKE 'ART_DEF_UNIT_MEMBER_FW_VERTOL%');
UPDATE ArtDefine_UnitMemberInfos SET Type = 'ART_DEF_UNIT_MEMBER_' || SUBSTR(UnitInfoType, 20) || '_ED' WHERE 
	(Type LIKE 'ART_DEF_UNIT_MEMBER_FW_CYBORG%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_FW_HOVERTANK%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_FW_RAILGUN_TANK%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_FW_SUPERCARRIER%' OR 
	Type LIKE 'ART_DEF_UNIT_MEMBER_FW_VERTOL%');
UPDATE ArtDefine_StrategicView SET StrategicViewType = 'ART_DEF_UNIT_' || SUBSTR(UnitInfoType, 13) || '_ED' 
	WHERE StrategicViewType IN 
	('ART_DEF_UNIT_FW_CYBORG', 'ART_DEF_UNIT_FW_HOVERTANK', 'ART_DEF_UNIT_FW_RAILGUN_TANK', 
	'ART_DEF_UNIT_FW_SUPERCARRIER', 'ART_DEF_UNIT_FW_VERTOL');
*/